### ISSUE TITLE
DISC: error when attempting to create docs

### ISSUE THREAD

**Issue by Xylambda** [mmngreco/sphinx-automated#15]
Hi,

I'm trying to set up the documentation for [this library](https://github.com/Xylambda/kalmanfilter), but I am getting the following errors:
### First Error
Appears the first time I run the command (below complete MWE)
```bash
(kalmanfilter)
Alejandro@Alejandro MINGW64 ~/sphinx-automated (master)
$ python -m sphinx_automated.run -c project.ini
Traceback (most recent call last):
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\run.py", line 102, in <module>
    main(PRJ_DIR, SRC_NAME, PRJ_NAME, AUTHOR, clean)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\run.py", line 54, in main
    make_doc_structure.main(PRJ_DIR, PRJ_NAME, AUTHOR)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\make_doc_structure.py", line 51, in main
    execute(CMD)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\utils.py", line 49, in execute
    for str_line in _exec(cmd):
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\utils.py", line 48, in _exec
    raise CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'sphinx-quickstart --quiet --sep --project='kalmanfilter' --author='Alejandro PS' --suffix=.rst --extensions=sphinx.ext.autosummary,sphinx.ext.autodoc,sphinx.ext.todo,sphinx.ext.viewcode,sphinx.ext.napoleon,sphinx.ext.mathjax --makefile --batchfile "C:\Users\Alejandro\kalmanfilter\docs"' returned non-zero exit status 2.
usage: sphinx-quickstart [OPTIONS] <PROJECT_DIR>
sphinx-quickstart: error: unrecognized arguments: C:\Users\Alejandro\kalmanfilter\docs
```

### Errors
The second and successive running errors (always using the same command specified below):
```bash
(kalmanfilter)
Alejandro@Alejandro MINGW64 ~
$ python -m sphinx_automated.run -c project.ini
Traceback (most recent call last):
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alejandro\Anaconda3\lib\site-packages\sphinx_automated\run.py", line 102, in <module>
    main(PRJ_DIR, SRC_NAME, PRJ_NAME, AUTHOR, clean)
  File "C:\Users\Alejandro\Anaconda3\lib\site-packages\sphinx_automated\run.py", line 40, in main
    PRJ_DIR = Path(PRJ_DIR)
  File "C:\Users\Alejandro\Anaconda3\lib\pathlib.py", line 1003, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\Alejandro\Anaconda3\lib\pathlib.py", line 658, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\Alejandro\Anaconda3\lib\pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### MWE
The steps I used:
1. Clone and install sphinx_automated.
2. Create a new `project.ini` file in `sphinx-automated` folder:
```code
[DEFAULT]
PRJ_DIR=/Users/Alejandro/kalmanfilter
SRC_DIR=kalmanfilter
PRJ_NAME=kalmanfilter
AUTHOR=Alejandro PS
```
3. Run the command (from `sphinx-automated` folder):
```python
python -m sphinx_automated.run -c project.ini
```

The file to my project is:
```code
C:\Users\Alejandro\kalmanfilter
```
and the project structure follows the README's scheme.

I think I am doing something wrong but I am not able to see where...

Thanks!

@mmngreco

**Comment by asdf8601** [comment]
Hi @Xylambda, 

Thank you for opening the issue. It looks like there is something wrong while your path is processed. What version of sphinx are you using?

I realize that you are using a windows SO, but the path in de config file doesn't looks like a windows path, you could try the below alternatives instead and update the issue.

`/c/Users/Alejandro/kalmanfilter/`

altenatively,

`C:\\Users\\Alejandro\\kalmanfilter`

**Comment by Xylambda** [comment]
Hi,

thanks for the response!

The sphinx version(s) I am using:
```bash
(kalmanfilter)
Alejandro@Alejandro MINGW64 ~
$ pip freeze | grep "sphinx"
sphinx-automated==0.1.0+17.gbc66db7
sphinx-rtd-theme==0.5.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
```

Regarding the solutions. The first path isn't working:
```bash
(kalmanfilter)
Alejandro@Alejandro MINGW64 ~/sphinx-automated (master)
$ python -m sphinx_automated.run -c project.ini
Traceback (most recent call last):
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\run.py", line 102, in <module>
    main(PRJ_DIR, SRC_NAME, PRJ_NAME, AUTHOR, clean)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\run.py", line 43, in main
    assert PRJ_DIR.exists(), f"The PRJ_DIR={PRJ_DIR} is not a valid path."
AssertionError: The PRJ_DIR=\c\Users\Alejandro\kalmanfilter is not a valid path.
```

And neither the second:
```bash
(kalmanfilter)
Alejandro@Alejandro MINGW64 ~/sphinx-automated (master)
$ python -m sphinx_automated.run -c project.ini
Traceback (most recent call last):
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Alejandro\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\run.py", line 102, in <module>
    main(PRJ_DIR, SRC_NAME, PRJ_NAME, AUTHOR, clean)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\run.py", line 54, in main
    make_doc_structure.main(PRJ_DIR, PRJ_NAME, AUTHOR)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\make_doc_structure.py", line 51, in main
    execute(CMD)
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\utils.py", line 49, in execute
    for str_line in _exec(cmd):
  File "C:\Users\Alejandro\sphinx-automated\sphinx_automated\utils.py", line 48, in _exec
    raise CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'sphinx-quickstart --quiet --sep --project='kalmanfilter' --author='Alejandro PS' --suffix=.rst --extensions=sphinx.ext.autosummary,sphinx.ext.autodoc,sphinx.ext.todo,sphinx.ext.viewcode,sphinx.ext.napoleon,sphinx.ext.mathjax --makefile --batchfile "C:\Users\Alejandro\kalmanfilter\docs"' returned non-zero exit status 2.
usage: sphinx-quickstart [OPTIONS] <PROJECT_DIR>
sphinx-quickstart: error: unrecognized arguments: C:\Users\Alejandro\kalmanfilter\docs
```

I thought the second path would work but, for some reason, it is not being recognized.

It fails when calling 
```bash
sphinx-quickstart --quiet --sep --project='kalmanfilter' --author='Alejandro PS' --suffix=.rst --extensions=sphinx.ext.autosummary,sphinx.ext.autodoc,sphinx.ext.todo,sphinx.ext.viewcode,sphinx.ext.napoleon,sphinx.ext.mathjax --makefile --batchfile "C:\Users\Alejandro\kalmanfilter\docs"
```

I ran the command directly into the bash and it worked and now I am even more confused.

**Comment by asdf8601** [comment]
> ```shell
> AssertionError: The PRJ_DIR=\c\Users\Alejandro\kalmanfilter is not a valid path.
> ```

only if you didn't notice it, in the path appears "\\" instead of "/". If you want to use the first one you need to escape it to make it works which means you should write "\\\\" instead.
This is tricky and a very common mistake using bash on windows.

About running the command manually, it's really weird. I will take a look as soon as possible.

**Comment by Xylambda** [comment]
I just checked this in a Mac and I had no problems. The bug seems to be related to the misspecification of Windows path. I am gonna close the issue. 
Apologies for the late response.
